UBUNTU: [Config] disable CONFIG_CRYPTO_AEGIS128_SIMD
After the update to gcc 10 we are experiencing the following build
errors on ARM:

crypto/aegis128-neon-inner.c: In function 'crypto_aegis128_init_neon':
crypto/aegis128-neon-inner.c:151:3: error: incompatible types when initializing type 'unsigned char' using type 'uint8x16_t'
  151 |   k ^ vld1q_u8(const0),
      |   ^
crypto/aegis128-neon-inner.c:152:3: error: incompatible types when initializing type 'unsigned char' using type 'uint8x16_t'
  152 |   k ^ vld1q_u8(const1),
      |   ^

Temporarily disable CONFIG_CRYPTO_AEGIS128_SIMD for now on ARM, until we
get a valid fix for this.

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>